parameters:
    uap_expression_browser:
        # SeaMonkey
        - regex: '(Iceape|SeaMonkey)/(\d+\.\d+)'
          name: $1
          version: '$2'

        # Camino
        - regex: 'Camino/(\d+\.\d+)'
          name: Camino
          version: '$1'

        #Fennec (Firefox for mobile)
        - regex: 'Fennec/(\d+\.\d+)'
          name: Fennec
          version: '$1'

        #MicroB
        - regex: 'Firefox.*Tablet browser (\d+\.\d+)'
          name: MicroB
          version: '$1'

        #Firefox
        - regex: 'Firefox/(\d+\.\d+)'
          name: Firefox
          version: '$1'
        - regex: '(BonEcho|GranParadiso|Lorentz|Minefield|Namoroka|Shiretoko)/(\d+\.\d+)'
          name: Firefox '$1'
          version: '$2'

        #Flock
        - regex: 'Flock/(\d+\.\d+)'
          name: Flock
          version: '$1'

        #RockMelt
        - regex: 'RockMelt/(\d+\.\d+)'
          name: RockMelt
          version: '$1'

        #Netscape
        - regex: '(?:Navigator|Netscape6)/(\d+\.\d+)'
          name: Netscape
          version: '$1'

        #Opera
        - regex: '(:?Opera Tablet.*Version|Opera/.+Opera Mobi.+Version|Safari.*OPR)/(\d+\.\d+)'
          name: Opera Mobile
          version: '$2'
        - regex: 'Opera Mini/(:?att/)?(\d+\.\d+)'
          name: Opera Mini
          version: '$2'
        - regex: 'Opera[/ ](?:9.80.*Version/)?(\d+\.\d+)'
          name: Opera
          version: '$1'

        #wOSBrowser
        - regex: '(?:hpw|web)OS/(\d+\.\d+)'
          name: wOSBrowser
          version: '$1'

        #Swiftfox
        - regex: 'Firefox/(\d+\.\d+).*\(Swiftfox\)'
          name: Swiftfox
          version: '$1'

        #Rekonq
        - regex: 'rekonq'
          name: Rekonq
          version: ''

        #Conkeror
        - regex: 'Conkeror/(\d+\.\d+)'
          name: Conkeror
          version: '$1'

        #Konqueror
        - regex: 'Konqueror/(\d+\.\d+)'
          name: Konqueror
          version: '$1'

        #Baidu Browser
        - regex: 'baidubrowser[/ ](\d+)'
          name: Baidu Browser
          version: '$1'

        #Yandex Browser
        - regex: 'YaBrowser/(\d+)'
          name: Yandex Browser
          version: '$1'

        #Chrome
        - regex: 'CrMo/(\d+\.\d+)'
          name: Chrome Mobile
          version: '$1'
        - regex: 'CriOS/(\d+\.\d+)'
          name: Chrome Mobile iOS
          version: '$1'
        - regex: 'Chrome/(\d+\.\d+).*Mobile'
          name: Chrome Mobile
          version: '$1'
        - regex: 'chromeframe/(\d+\.\d+)'
          name: Chrome Frame
          version: '$1'
        - regex: 'Chrome/(\d+\.\d+)'
          name: Chrome
          version: '$1'
        - regex: 'Chromium/(\d+\.\d+)'
          name: Chromium
          version: '$1'

        #UC Browser
        - regex: 'UC[ ]?Browser[ /](\d+\.\d+)'
          name: UC Browser
          version: '$1'
        - regex: '(?:UC Browser|UCBrowser|UCWEB)(\d+\.\d+)'
          name: UC Browser
          version: '$1'

        #Tizen Browser
        - regex: '(?:Tizen|SLP) Browser/(\d+\.\d+)'
          name: Tizen Browser
          version: '$1'

        #Epiphany
        - regex: 'Epiphany/(\d+\.\d+)'
          name: Epiphany
          version: '$1'

        #Fireweb Navigator
        - regex: 'Fireweb Navigator/(\d+\.\d+)'
          name: Fireweb Navigator
          version: '$1'

        #Jasmine
        - regex: 'Jasmine[ /](\d+\.\d+)'
          name: Jasmine
          version: '$1'

        #Lynx
        - regex: 'Lynx/(\d+\.\d+)'
          name: Lynx
          version: '$1'

        #Midori
        - regex: 'Midori/(\d+\.\d+)'
          name: Midori
          version: '$1'

        #NCSA Mosaic
        - regex: 'NCSA_Mosaic/(\d+\.\d+)'
          name: NCSA Mosaic
          version: '$1'

        #ABrowse
        - regex: 'ABrowse (\d+\.\d+)'
          name: ABrowse
          version: '$1'

        #Amaya
        - regex: 'amaya/(\d+\.\d+)'
          name: Amaya
          version: '$1'

        #Amiga Voyager
        - regex: 'AmigaVoyager/(\d+\.\d+)'
          name: Amiga Voyager
          version: '$1'

        #Amiga Aweb
        - regex: 'Amiga-Aweb/(\d+\.\d+)'
          name: Amiga Aweb
          version: '$1'

        #Arora
        - regex: 'Arora/(\d+\.\d+)'
          name: Arora
          version: '$1'

        #Beonex
        - regex: 'Beonex/(\d+\.\d+)'
          name: Beonex
          version: '$1'

        #BlackBerry Browser
        - regex: 'Black[bB]erry|PlayBook|BB10'
          name: BlackBerry Browser
          version: ''

        #BrowseX
        - regex: 'BrowseX \((\d+\.\d+)'
          name: BrowseX
          version: '$1'

        #Cheshire
        - regex: 'Cheshire/(\d+\.\d+)'
          name: Cheshire
          version: '$1'

        #CometBird
        - regex: 'CometBird/(\d+\.\d+)'
          name: CometBird
          version: '$1'

        #Dillo
        - regex: 'Dillo/(\d+\.\d+)'
          name: Dillo
          version: '$1'

        #Dolphin
        - regex: 'Dolfin/(\d+\.\d+)|dolphin'
          name: Dolphin
          version: '$1'

        #Elinks
        - regex: 'Elinks/(\d+\.\d+)'
          name: Elinks
          version: '$1'

        #Firebird
        - regex: 'Firebird/(\d+\.\d+)'
          name: Firebird
          version: '$1'

        #Fluid
        - regex: 'Fluid/(\d+\.\d+)'
          name: Fluid
          version: '$1'

        #Galeon
        - regex: 'Galeon/(\d+\.\d+)'
          name: Galeon
          version: '$1'

        #Google Earth
        - regex: 'Google Earth/(\d+\.\d+)'
          name: Google Earth
          version: '$1'

        #HotJava
        - regex: 'HotJava/(\d+\.\d+)'
          name: HotJava
          version: '$1'

        #IBrowse
        - regex: 'IBrowse[ /](\d+\.\d+)'
          name: IBrowse
          version: '$1'

        #iCab
        - regex: 'iCab[ /](\d+\.\d+)'
          name: iCab
          version: '$1'

        #Internet Explorer
        - regex: 'IEMobile[ /](\d+\.\d+)'
          name: IE Mobile
          version: '$1'
        - regex: 'MSIE (\d+\.\d+).*XBLWP7'
          name: IE Mobile
          version: '$1'
        - regex: 'MSIE (\d+\.\d+)'
          name: Internet Explorer
          version: '$1'

        #Iron
        - regex: 'Iron/(\d+\.\d+)'
          name: Iron
          version: '$1'

        #Kapiko
        - regex: 'Kapiko/(\d+\.\d+)'
          name: Kapiko
          version: '$1'

        #Kazehakase
        - regex: 'Kazehakase/(\d+\.\d+)'
          name: Kazehakase
          version: '$1'

        #Kindle Browser
        - regex: 'Kindle/(\d+\.\d+)'
          name: Kindle Browser
          version: '$1'

        #K-meleon
        - regex: 'K-meleon/(\d+\.\d+)'
          name: K-meleon
          version: '$1'

        #Lightning
        - regex: 'Lightning/(\d+\.\d+)'
          name: Lightning
          version: '$1'

        #Links
        - regex: 'Links \((\d+\.\d+)'
          name: Links
          version: '$1'

        #Maxthon
        - regex: 'Maxthon (\d+\.\d+)'
          name: Maxthon
          version: '$1'
        - regex: '(?:Maxthon|MyIE2|Uzbl|Shiira)'
          name: Maxthon
          version: ''

        #Openwave Mobile Browser
        - regex: 'UP.Browser/(\d+\.\d+)'
          name: Openwave Mobile Browser
          version: '$1'

        #OmniWeb
        - regex: 'OmniWeb/[v]?(\d+\.\d+)'
          name: OmniWeb
          version: '$1'

        #Phoenix
        - regex: 'Phoenix/(\d+\.\d+)'
          name: Phoenix
          version: '$1'

        #Mobile Silk
        - regex: 'Silk/(\d+\.\d+)'
          name: Mobile Silk
          version: '$1'

        #Nokia Browser
        - regex: '(?:NokiaBrowser|BrowserNG)/(\d+\.\d+)'
          name: Nokia Browser
          version: '$1'
        - regex: 'Series60/5\.0'
          name: Nokia Browser
          version: '7.0'
        - regex: 'Series60/(\d+\.\d+)'
          name: Nokia OSS Browser
          version: '$1'
        - regex: 'S40OviBrowser/(\d+\.\d+)'
          name: Nokia Ovi Browser
          version: '$1'
        - regex: '^Nokia|Nokia[EN]?\d+'
          name: Nokia Browser
          version: ''

        #NetFront
        - regex: 'NetFrontLifeBrowser/(\d+\.\d+)'
          name: NetFront Life
          version: '$1'
        - regex: 'NetFront/(\d+\.\d+)'
          name: NetFront
          version: '$1'
        - regex: 'PLAYSTATION|NINTENDO 3|AppleWebKit.+ NX/\d+\.\d+\.\d+'
          name: NetFront
          version: ''

        #Obigo
        - regex: 'Obigo[ ]?(?:InternetBrowser|Browser)?[ /]([A-Za-z0-9]*)'
          name: Obigo
          version: '$1'
        - regex: 'Obigo|Teleca'
          name: Obigo
          version: ''

        #Palm Blazer
        - regex: 'Blazer/(\d+\.\d+)'
          name: Palm Blazer
          version: '$1'
        - regex: 'Pre/(\d+\.\d+)'
          name: Palm Pre
          version: '$1'

        #Polaris
        - regex: '(?:Polaris|Embider)/(\d+\.\d+)'
          name: Polaris
          version: '$1'

        #Snowshoe
        - regex: 'Snowshoe/(\d+\.\d+)'
          name: Snowshoe
          version: '$1'

        #Safari
        - regex: '(?:iPod|iPad|iPhone).+Version/(\d+\.\d+)'
          name: Mobile Safari
          version: '$1'
        - regex: 'Version/(\d+\.\d+).*Mobile.*Safari/'
          name: Mobile Safari
          version: '$1'
        - regex: '(?:iPod|iPhone|iPad)'
          name: Mobile Safari
          version: ''
        - regex: 'Version/(\d+\.\d+).*Safari/|Safari/\d+'
          name: Safari
          version: '$1'

        #Android Browser
        - regex: 'Android'
          name: Android Browser
          version: ''