parameters:
    uap_expression_os:
        ##########
        # Tizen
        ##########
        - regex: 'Tizen'
          name: 'Tizen'
          version: ''



        ##########
        # Android
        ##########
        - regex: 'Android[ /](\d+\.\d+)'
          name: 'Android'
          version: '$1'


        - regex: 'Android|Silk-Accelerated=[a-z]{4,5}'
          name: 'Android'
          version: ''



        ##########
        # Linux
        ##########
        - regex: 'Linux; .*((?:Arch Linux|Debian|Knoppix|Mint|Ubuntu|Kubuntu|Xubuntu|Lubuntu|Fedora|Red Hat|Mandriva|Gentoo|Slackware|SUSE|Puppy|CentOS|BackTrack|YunOs|Presto))[ /](\d+\.\d+)'
          name: '$1'
          version: '$2'


        - regex: '((?:Arch Linux|Debian|Knoppix|Mint|Ubuntu|Kubuntu|Xubuntu|Lubuntu|Fedora|Red Hat|Mandriva|Gentoo|Slackware|SUSE|Puppy|CentOS|BackTrack|YunOs|Presto));.*Linux'
          name: '$1'
          version: ''


        - regex: 'Linux; |Linux (?:x86_64|zbov|i686)'
          name: 'Linux'
          version: ''



        ##########
        # Windows Mobile
        ##########
        - regex: 'Windows Phone (?:OS)?[ ]?(\d+\.\d+)'
          name: 'Windows Phone'
          version: '$1'


        - regex: 'XBLWP7|Windows Phone'
          name: 'Windows Phone'
          version: ''

        - regex: 'Windows CE'
          name: 'Windows CE'
          version: ''


        - regex: '(?:IEMobile|Windows Mobile)(?: (\d+\.\d+))?'
          name: 'Windows Mobile'
          version: '$1'


        - regex: 'Windows NT 6.2; ARM;'
          name: 'Windows RT'
          version: ''



        ##########
        # Windows
        ##########
        - regex: 'CYGWIN_NT-6.2|Windows NT 6.2|Windows 8'
          name: 'Windows 8'
          version: '8'


        - regex: 'CYGWIN_NT-6.1|Windows NT 6.1|Windows 7'
          name: 'Windows 7'
          version: '7'


        - regex: 'CYGWIN_NT-6.0|Windows NT 6.0|Windows Vista'
          name: 'Windows Vista'
          version: 'Vista'


        - regex: 'CYGWIN_NT-5.2|Windows NT 5.2|Windows Server 2003 / XP x64'
          name: 'Windows Server 2003'
          version: 'Server 2003'


        - regex: 'CYGWIN_NT-5.1|Windows NT 5.1|Windows XP'
          name: 'Windows XP'
          version: 'XP'


        - regex: 'CYGWIN_NT-5.0|Windows NT 5.0|Windows 2000'
          name: 'Windows 2000'
          version: '2000'


        - regex: 'CYGWIN_NT-4.0|Windows NT 4.0|WinNT|Windows NT'
          name: 'Windows NT'
          version: 'NT'


        - regex: 'CYGWIN_ME-4.90|Win 9x 4.90|Windows ME'
          name: 'Windows ME'
          version: 'ME'


        - regex: 'CYGWIN_98-4.10|Win98|Windows 98'
          name: 'Windows 98'
          version: '98'


        - regex: 'CYGWIN_95-4.0|Win32|Win95|Windows 95|Windows_95'
          name: 'Windows 95'
          version: '95'


        - regex: 'Windows 3.1'
          name: 'Windows 3.1'
          version: '3.1'


        - regex: 'Windows'
          name: 'Windows'
          version: ''



        ##########
        # Mac
        ##########
        - regex: 'Mac OS X (\d+[_.]\d+)'
          name: 'Mac'

          version: '$1'

        - regex: 'Darwin|Macintosh|Mac_PowerPC|PPC|Mac PowerPC'
          name: 'Mac'
          version: ''



        ##########
        # iOS
        ##########
        - regex: '(?:CPU OS|iPhone OS) (\d+_\d+)'
          name: 'iOS'

          version: '$1'

        - regex: '(?:iPhone|iPad|iPod)(?:.*Mac OS X.*Version/(\d+\.\d+)|; Opera)'
          name: 'iOS'
          version: '$1'



        ##########
        # webOS
        ##########
        - regex: '(?:webOS|Palm webOS)(?:/(\d+\.\d+))?'
          name: 'webOS'
          version: '$1'


        - regex: '(?:PalmOS|Palm OS)(?:/(\d+\.\d+))?'
          name: 'PalmOS'
          version: ''



        ##########
        # ChromeOS
        ##########
        - regex: 'CrOS [a-z0-9_]+ (\d+\.\d+)'
          name: 'Chrome OS'
          version: '$1'



        ##########
        # BlackBerry
        ##########
        - regex: '(?:BB10;.+Version|Black[Bb]erry[0-9a-z]+|Black[Bb]erry.+Version)/(\d+\.\d+)'
          name: 'BlackBerry OS'
          version: '$1'


        - regex: 'RIM Tablet OS (\d+\.\d+)'
          name: 'BlackBerry Tablet OS'
          version: '$1'


        - regex: 'RIM Tablet OS|QNX|Play[Bb]ook'
          name: 'BlackBerry Tablet OS'
          version: ''


        - regex: 'Black[Bb]erry'
          name: 'BlackBerry OS'
          version: ''



        ##########
        # Symbian
        ##########
        - regex: 'Symbian[Oo][Ss]/(\d+\.\d+)'
          name: 'Symbian OS'
          version: '$1'


        - regex: 'Symbian/3.+NokiaBrowser/7\.3'
          name: 'Symbian'
          version: '^3 Anna'


        - regex: 'Symbian/3.+NokiaBrowser/7\.4'
          name: 'Symbian'
          version: '^3 Belle'


        - regex: 'Symbian[/]?3'
          name: 'Symbian^3'
          version: '^3'


        - regex: '(?:Series 60|SymbOS|S60)(?:[ /]?(\d+\.\d+|V\d+))?'
          name: 'Symbian OS Series 60'
          version: '$1'


        - regex: 'Series40'
          name: 'Symbian OS Series 40'
          version: ''


        - regex: 'MeeGo|WeTab'
          name: 'MeeGo'
          version: ''


        - regex: 'Symbian [Oo][Ss]|SymbOS'
          name: 'Symbian OS'
          version: ''


        - regex: 'Nokia'
          name: 'Symbian'
          version: ''



        ##########
        # Firefox OS
        ##########
        - regex: '(?:Mobile|Tablet);.+Firefox/\d+\.\d+'
          name: 'Firefox OS'
          version: ''



        ##########
        # Bada
        ##########
        - regex: 'bada'
          name: 'Bada'
          version: ''



        ##########
        # Brew
        ##########
        - regex: '(?:Brew MP|BREW|BMP)(?:[ /](\d+\.\d+))?'
          name: 'Brew'
          version: '$1'



        ##########
        # Web TV
        ##########
        - regex: 'GoogleTV[ /](\d+\.\d+)|GoogleTV'
          name: 'Google TV'
          version: '$1'


        - regex: 'AppleTV/(\d+\.\d+)'
          name: 'Apple TV'
          version: '$1'


        - regex: 'WebTV/(\d+\.\d+)'
          name: 'WebTV'
          version: '$1'



        ##########
        # Unix
        ##########
        - regex: 'SunOS'
          name: 'Solaris'
          version: ''


        - regex: 'AIX'
          name: 'AIX'
          version: ''


        - regex: 'HP-UX'
          name: 'HP-UX'
          version: ''


        - regex: 'FreeBSD'
          name: 'FreeBSD'
          version: ''


        - regex: 'NetBSD'
          name: 'NetBSD'
          version: ''


        - regex: 'OpenBSD'
          name: 'OpenBSD'
          version: ''


        - regex: 'DragonFly'
          name: 'DragonFly'
          version: ''


        - regex: 'Syllable'
          name: 'Syllable'
          version: ''


        - regex: 'IRIX'
          name: 'IRIX'
          version: ''


        - regex: 'OSF1'
          name: 'OSF1'
          version: ''



        ##########
        # Gaming Console
        ##########
        - regex: 'Nintendo Wii'
          name: 'Nintendo'
          version: 'Wii'


        - regex: 'PlayStation 3|PlayStation3'
          name: 'PlayStation'
          version: '3'


        - regex: 'Xbox|KIN\.(?:One|Two)'
          name: 'Xbox'
          version: '360'



        ##########
        # Mobile Gaming Console
        ##########
        - regex: 'Nitro|Nintendo ([3]?DS[i]?)'
          name: 'Nintendo Mobile'
          version: '$1'


        - regex: 'PlayStation ((?:Portable|Vita))'
          name: 'PlayStation'
          version: '$1'



        ##########
        # IBM
        ##########
        - regex: 'OS/2'
          name: 'OS/2'
          version: ''



        ##########
        # Simulators
        ##########
        - regex: '(Talkatone|WinWAP)'
          name: '$1'
          version: ''



        ##########
        # Bot
        ##########
        - regex: '(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves/Teoma|ia_archiver|ScoutJet|Gulper Web Bot|EmailWolf|grub-client|Download Demon|OmniWeb|SearchExpress|Microsoft URL Control|bot|borg|yahoo|slurp|msnbot|msrbot|openbot|archiver|netresearch|transcoder|crawler|lycos|scooter|altavista|teoma|gigabot|baiduspider|blitzbot|oegp|charlotte|furlbot|http%20client|polybot|htdig|ichiro|mogimogi|larbin|pompos|scrubby|searchsight|seekbot|semanticdiscovery|silk|snappy|speedy|spider|voila|vortex|voyager|zao|zeal|fast-webcrawler|converacrawler|dataparksearch|findlinksYottaaMonitor|BrowserMob|HttpMonitor|YandexBot|Slurp|BingPreview|PagePeeker|ThumbShotsBot|WebThumb|URL2PNG|ZooShot|GomezA|Catchpoint bot|Willow Internet Crawler|Google SketchUp|Read%20Later|Minimo|Pingdom.com|facebookexternalhit|Twitterbot|RackspaceBot)'
          name: 'Bot'
          version: ''

