parameters:
    uap_mappping_browser:
        - id: 1
          name: ABrowse
        - id: 2
          name: Amaya
        - id: 3
          name: Android Browser
        - id: 4
          name: Arora
        - id: 5
          name: Amiga Voyager
        - id: 6
          name: Amiga Aweb
        - id: 7
          name: BlackBerry Browser
        - id: 8
          name: Baidu Browser
        - id: 9
          name: Beonex
        - id: 10
          name: BrowseX
        - id: 11
          name: Camino
        - id: 12
          name: Chrome Frame
        - id: 13
          name: Chrome
        - id: 14
          name: Chrome Mobile iOS
        - id: 15
          name: Conkeror
        - id: 16
          name: Chrome Mobile
        - id: 17
          name: CometBird
        - id: 18
          name: Chromium
        - id: 19
          name: Cheshire
        - id: 20
          name: Dolphin
        - id: 21
          name: Dillo
        - id: 22
          name: Elinks
        - id: 23
          name: Epiphany
        - id: 24
          name: Firebird
        - id: 25
          name: Fluid
        - id: 26
          name: Fennec
        - id: 27
          name: Firefox
        - id: 28
          name: Flock
        - id: 29
          name: Fireweb Navigator
        - id: 30
          name: Galeon
        - id: 31
          name: Google Earth
        - id: 32
          name: HotJava
        - id: 33
          name: IBrowse
        - id: 34
          name: iCab
        - id: 35
          name: Internet Explorer
        - id: 36
          name: IE Mobile
        - id: 37
          name: Iron
        - id: 38
          name: Jasmine
        - id: 39
          name: Kindle Browser
        - id: 40
          name: K-meleon
        - id: 41
          name: Konqueror
        - id: 42
          name: Kapiko
        - id: 43
          name: Kazehakase
        - id: 44
          name: Lightning
        - id: 45
          name: Links
        - id: 46
          name: Lynx
        - id: 47
          name: MicroB
        - id: 48
          name: NCSA Mosaic
        - id: 49
          name: Mobile Safari
        - id: 50
          name: Midori
        - id: 51
          name: Mobile Silk
        - id: 52
          name: Maxthon
        - id: 53
          name: Nokia Browser
        - id: 54
          name: NetFront
        - id: 55
          name: NetFront Life
        - id: 56
          name: Netscape
        - id: 57
          name: Obigo
        - id: 58
          name: Opera Mini
        - id: 59
          name: Opera Mobile
        - id: 60
          name: Opera
        - id: 61
          name: Openwave Mobile Browser
        - id: 62
          name: OmniWeb
        - id: 63
          name: Palm Blazer
        - id: 64
          name: Palm Pre
        - id: 65
          name: Phoenix
        - id: 66
          name: Rekonq
        - id: 67
          name: RockMelt
        - id: 68
          name: Safari
        - id: 69
          name: SeaMonkey
        - id: 70
          name: Snowshoe
        - id: 71
          name: Swiftfox
        - id: 72
          name: Tizen Browser
        - id: 73
          name: UC Browser
        - id: 74
          name: wOSBrowser
        - id: 75
          name: Yandex Browser

    uap_mappping_browser_family:
        - id: 1
          name: Android Browser
          acronym:
            - AN
        - id: 2
          name: BlackBerry Browser
          acronym:
            - BB
        - id: 3
          name: Chrome
          acronym:
            - CH
            - CM
            - CI
            - CF
            - CR
            - RM
        - id: 4
          name: Firefox
          acronym:
            - FF
            - FE
            - SX
            - FB
            - PX
            - MB
        - id: 5
          name: Internet Explorer
          acronym:
            - IE
            - IM
        - id: 6
          name: Konqueror
          acronym:
            - KO
        - id: 7
          name: NetFront
          acronym:
            - NF
        - id: 8
          name: Nokia Browser
          acronym:
            - NB
        - id: 9
          name: Opera
          acronym:
            - OP
            - OM
            - OI
        - id: 10
          name: Safari
          acronym:
            - SF
            - MF