parameters:
    uap_mappping_device_type:
        - id: 1
          name: desktop
        - id: 2
          name: smartphone
        - id: 3
          name: tablet
        - id: 4
          name: feature phone
        - id: 5
          name: console
        - id: 6
          name: tv
        - id: 7
          name: car browser

    uap_mappping_device_brand:
        - id: 1
          name: Acer
        - id: 2
          name: Airness
        - id: 3
          name: Alcatel
        - id: 4
          name: Amoi
        - id: 5
          name: Apple
        - id: 6
          name: Asus
        - id: 7
          name: Avvio
        - id: 8
          name: Audiovox
        - id: 9
          name: Becker
        - id: 10
          name: Bird
        - id: 11
          name: Beetel
        - id: 12
          name: BenQ
        - id: 13
          name: BenQ-Siemens
        - id: 14
          name: Cricket
        - id: 15
          name: Compal
        - id: 16
          name: Capitel
        - id: 17
          name: Dbtel
        - id: 18
          name: DoCoMo
        - id: 19
          name: Dicam
        - id: 20
          name: Dell
        - id: 21
          name: Dopod
        - id: 22
          name: Ericsson
        - id: 23
          name: Ezio
        - id: 24
          name: Ericy
        - id: 25
          name: eTouch
        - id: 26
          name: Ezze
        - id: 27
          name: Fly
        - id: 28
          name: Gionee
        - id: 29
          name: Google
        - id: 30
          name: Gradiente
        - id: 31
          name: Grundig
        - id: 32
          name: Haier
        - id: 33
          name: HP
        - id: 34
          name: HTC
        - id: 35
          name: Huawei
        - id: 36
          name: iKoMo
        - id: 37
          name: i-mate
        - id: 38
          name: Innostream
        - id: 39
          name: i-mobile
        - id: 40
          name: INQ
        - id: 41
          name: Karbonn
        - id: 42
          name: KDDI
        - id: 43
          name: Kindle
        - id: 44
          name: Konka
        - id: 45
          name: Kyocera
        - id: 46
          name: Lanix
        - id: 47
          name: LCT
        - id: 48
          name: Lenovo
        - id: 49
          name: LG
        - id: 50
          name: LGUPlus
        - id: 51
          name: MicroMax
        - id: 52
          name: Mio
        - id: 53
          name: Motorola
        - id: 54
          name: Microsoft
        - id: 55
          name: Mitsubishi
        - id: 56
          name: MyPhone
        - id: 57
          name: NEC
        - id: 58
          name: NGM
        - id: 59
          name: Nintendo
        - id: 60
          name: Nokia
        - id: 61
          name: Newgen
        - id: 62
          name: Nexian
        - id: 63
          name: Onda
        - id: 64
          name: OPPO
        - id: 65
          name: Orange
        - id: 66
          name: O2
        - id: 67
          name: Panasonic
        - id: 68
          name: Philips
        - id: 69
          name: Palm
        - id: 70
          name: phoneOne
        - id: 71
          name: Pantech
        - id: 72
          name: Qtek
        - id: 73
          name: RIM
        - id: 74
          name: Rover
        - id: 75
          name: Samsung
        - id: 76
          name: Sega
        - id: 77
          name: Sony Ericsson
        - id: 78
          name: Softbank
        - id: 79
          name: Sagem
        - id: 80
          name: Sharp
        - id: 81
          name: Siemens
        - id: 82
          name: Sendo
        - id: 83
          name: Sony
        - id: 84
          name: Spice
        - id: 85
          name: Sanyo
        - id: 86
          name: Tesla
        - id: 87
          name: TCL
        - id: 88
          name: Telit
        - id: 89
          name: TiPhone
        - id: 90
          name: TIANYU
        - id: 91
          name: T-Mobile
        - id: 92
          name: Toplux
        - id: 93
          name: Toshiba
        - id: 94
          name: UTStarcom
        - id: 95
          name: Videocon
        - id: 96
          name: Vertu
        - id: 97
          name: Vitelcom
        - id: 98
          name: VK Mobile
        - id: 99
          name: Voxtel
        - id: 100
          name: Web TV
        - id: 101
          name: WellcoM
        - id: 102
          name: Wonu
        - id: 103
          name: Unknown
        - id: 104
          name: Zonda
        - id: 105
          name: ZTE