parameters:
    uap_mappping_os_short:
        - id: 1
          name: AIX
        - id: 2
          name: AND
        - id: 3
          name: ATV
        - id: 4
          name: ARL
        - id: 5
          name: BTR
        - id: 6
          name: SBA
        - id: 7
          name: BLB
        - id: 8
          name: QNX
        - id: 9
          name: BOT
        - id: 10
          name: BMP
        - id: 11
          name: CES
        - id: 12
          name: COS
        - id: 13
          name: DEB
        - id: 14
          name: DFB
        - id: 15
          name: FED
        - id: 16
          name: FOS
        - id: 17
          name: BSD
        - id: 18
          name: GNT
        - id: 19
          name: GTV
        - id: 20
          name: HPX
        - id: 21
          name: IRI
        - id: 22
          name: KNO
        - id: 23
          name: KBT
        - id: 24
          name: LIN
        - id: 25
          name: LBT
        - id: 26
          name: MAC
        - id: 27
          name: MDR
        - id: 28
          name: SMG
        - id: 29
          name: MIN
        - id: 30
          name: NBS
        - id: 31
          name: WII
        - id: 32
          name: NDS
        - id: 33
          name: OS2
        - id: 34
          name: T64
        - id: 35
          name: OBS
        - id: 36
          name: PSP
        - id: 37
          name: PS3
        - id: 38
          name: PRS
        - id: 39
          name: PPY
        - id: 40
          name: RHT
        - id: 41
          name: SSE
        - id: 42
          name: SLW
        - id: 43
          name: SOS
        - id: 44
          name: SYL
        - id: 45
          name: SYM
        - id: 46
          name: SYS
        - id: 47
          name: S40
        - id: 48
          name: S60
        - id: 49
          name: SY3
        - id: 50
          name: TKT
        - id: 51
          name: TIZ
        - id: 52
          name: UBT
        - id: 53
          name: WTV
        - id: 54
          name: WWP
        - id: 55
          name: WIN
        - id: 56
          name: W2K
        - id: 57
          name: W31
        - id: 58
          name: WI7
        - id: 59
          name: WI8
        - id: 60
          name: W95
        - id: 61
          name: W98
        - id: 62
          name: WCE
        - id: 63
          name: WME
        - id: 64
          name: WMO
        - id: 65
          name: WNT
        - id: 66
          name: WPH
        - id: 67
          name: WRT
        - id: 68
          name: WS3
        - id: 69
          name: WVI
        - id: 70
          name: WXP
        - id: 71
          name: XBX
        - id: 72
          name: XBT
        - id: 73
          name: YNS
        - id: 74
          name: IOS
        - id: 75
          name: POS
        - id: 76
          name: WOS

    uap_mappping_desktop_os:
        - id: 1
          name: IBM
        - id: 2
          name: Linux
        - id: 3
          name: Mac
        - id: 4
          name: Unix
        - id: 5
          name: Windows

    uap_mappping_os_family:
        - id: 1
          name: Android
          acronym:
            - AND
        - id: 2
          name: Apple TV
          acronym:
            - ATV
        - id: 3
          name: BlackBerry
          acronym:
            - BLB
        - id: 4
          name: Bot
          acronym:
            - BOT
        - id: 5
          name: Brew
          acronym:
            - BMP
        - id: 6
          name: Chrome OS
          acronym:
            - COS
        - id: 7
          name: Firefox OS
          acronym:
            - FOS
        - id: 8
          name: Gaming Console
          acronym:
            - WII
            - PS3
        - id: 9
          name: Google TV
          acronym:
            - GTV
        - id: 10
          name: IBM
          acronym:
            - OS2
        - id: 11
          name: iOS
          acronym:
            - IOS
        - id: 12
          name: Linux
          acronym:
            - LIN
            - ARL
            - DEB
            - KNO
            - MIN
            - UBT
            - KBT
            - XBT
            - LBT
            - FED
            - RHT
            - MDR
            - GNT
            - SLW
            - SSE
            - PPY
            - CES
            - BTR
            - YNS
            - PRS
        - id: 13
          name: Mac
          acronym:
            - MAC
        - id: 14
          name: Mobile Gaming Console
          acronym:
            - PSP
            - NDS
            - XBX
        - id: 15
          name: Other Mobile
          acronym:
            - WOS
            - POS
            - QNX
            - SBA
            - TIZ
        - id: 16
          name: Simulator
          acronym:
            - TKT
            - WWP
        - id: 17
          name: Symbian
          acronym:
            - SYM
            - SYS
            - SY3
            - S60
            - S40
            - SMG
        - id: 18
          name: Unix
          acronym:
            - SOS
            - AIX
            - HPX
            - BSD
            - NBS
            - OBS
            - DFB
            - SYL
            - IRI
            - T64
        - id: 19
          name: WebTV
          acronym:
            - WTV
        - id: 20
          name: Windows
          acronym:
            - WI8
            - WI7
            - WVI
            - WS3
            - WXP
            - W2K
            - WNT
            - WME
            - W98
            - W95
            - WRT
            - W31
            - WIN
        - id: 21
          name: Windows Mobile
          acronym:
            - WPH
            - WMO
            - WCE