parameters:
    uap_definition_device_brand:
        AC: Acer
        AI: Airness
        AL: Alcatel
        AO: Amoi
        AP: Apple
        AU: Asus
        AV: Avvio
        AX: Audiovox
        BE: Becker
        BI: Bird
        BL: Beetel
        BQ: BenQ
        BS: BenQ-Siemens
        CK: Cricket
        CL: Compal
        CT: Capitel
        DB: Dbtel
        DC: DoCoMo
        DI: Dicam
        DL: Dell
        DP: Dopod
        EC: Ericsson
        EI: Ezio
        ER: Ericy
        ET: eTouch
        EZ: Ezze
        FL: Fly
        GI: Gionee
        GO: Google
        GR: Gradiente
        GU: Grundig
        HA: Haier
        HP: HP
        HT: HTC
        HU: Huawei
        IK: iKoMo
        IM: i-mate
        IN: Innostream
        IO: i-mobile
        IQ: INQ
        KA: Karbonn
        KD: KDDI
        KN: Kindle
        KO: Konka
        KY: Kyocera
        LA: Lanix
        LC: LCT
        LE: Lenovo
        LG: LG
        LU: LGUPlus
        MI: MicroMax
        MO: Mio
        MR: Motorola
        MS: Microsoft
        MT: Mitsubishi
        MY: MyPhone
        NE: NEC
        NG: NGM
        NI: Nintendo
        NK: Nokia
        NW: Newgen
        NX: Nexian
        OD: Onda
        OP: OPPO
        OR: Orange
        OT: O2
        PA: Panasonic
        PH: Philips
        PM: Palm
        PO: phoneOne
        PT: Pantech
        QT: Qtek
        RM: RIM
        RO: Rover
        SA: Samsung
        SD: Sega
        SE: Sony Ericsson
        SF: Softbank
        SG: Sagem
        SH: Sharp
        SI: Siemens
        SN: Sendo
        SO: Sony
        SP: Spice
        SY: Sanyo
        TA: Tesla
        TC: TCL
        TE: Telit
        TH: TiPhone
        TI: TIANYU
        TM: T-Mobile
        TO: Toplux
        TS: Toshiba
        UT: UTStarcom
        VD: Videocon
        VE: Vertu
        VI: Vitelcom
        VK: VK Mobile
        VO: Voxtel
        WB: Web TV
        WE: WellcoM
        WO: Wonu
        XX: Unknown
        ZO: Zonda
        ZT: ZTE