parameters:
    uap_definition_os_family:
        Android:
          - AND
        Apple TV:
          - ATV
        BlackBerry:
          - BLB
        Bot:
          - BOT
        Brew:
          - BMP
        Chrome OS:
          - COS
        Firefox OS:
          - FOS
        Gaming Console:
          - WII
          - PS3
        Google TV:
          - GTV
        IBM:
          - OS2
        iOS:
          - IOS
        Linux:
          - LIN
          - ARL
          - DEB
          - KNO
          - MIN
          - UBT
          - KBT
          - XBT
          - LBT
          - FED
          - RHT
          - MDR
          - GNT
          - SLW
          - SSE
          - PPY
          - CES
          - BTR
          - YNS
          - PRS
        Mac:
          - MAC
        Mobile Gaming Console:
          - PSP
          - NDS
          - XBX
        Other Mobile:
          - WOS
          - POS
          - QNX
          - SBA
          - TIZ
        Simulator:
          - TKT
          - WWP
        Symbian:
          - SYM
          - SYS
          - SY3
          - S60
          - S40
          - SMG
        Unix:
          - SOS
          - AIX
          - HPX
          - BSD
          - NBS
          - OBS
          - DFB
          - SYL
          - IRI
          - T64
        WebTV:
          - WTV
        Windows:
          - WI8
          - WI7
          - WVI
          - WS3
          - WXP
          - W2K
          - WNT
          - WME
          - W98
          - W95
          - WRT
          - W31
          - WIN
        Windows Mobile:
          - WPH
          - WMO
          - WCE