parameters:
    uap_definition_os_short:
        AIX: AIX
        Android: AND
        Apple TV: ATV
        Arch Linux: ARL
        BackTrack: BTR
        Bada: SBA
        BlackBerry OS: BLB
        BlackBerry Tablet OS: QNX
        Bot: BOT
        Brew: BMP
        CentOS: CES
        Chrome OS: COS
        Debian: DEB
        DragonFly: DFB
        Fedora: FED
        Firefox OS: FOS
        FreeBSD: BSD
        Gentoo: GNT
        Google TV: GTV
        HP-UX: HPX
        IRIX: IRI
        Knoppix: KNO
        Kubuntu: KBT
        Linux: LIN
        Lubuntu: LBT
        Mac: MAC
        Mandriva: MDR
        MeeGo: SMG
        Mint: MIN
        NetBSD: NBS
        Nintendo: WII
        Nintendo Mobile: NDS
        OS/2: OS2
        OSF1: T64
        OpenBSD: OBS
        PlayStation: PSP
        PlayStation 3: PS3
        Presto: PRS
        Puppy: PPY
        Red Hat: RHT
        SUSE: SSE
        Slackware: SLW
        Solaris: SOS
        Syllable: SYL
        Symbian: SYM
        Symbian OS: SYS
        Symbian OS Series 40: S40
        Symbian OS Series 60: S60
        Symbian^3: SY3
        Talkatone: TKT
        Tizen: TIZ
        Ubuntu: UBT
        WebTV: WTV
        WinWAP: WWP
        Windows: WIN
        Windows 2000: W2K
        Windows 3.1: W31
        Windows 7: WI7
        Windows 8: WI8
        Windows 95: W95
        Windows 98: W98
        Windows CE: WCE
        Windows ME: WME
        Windows Mobile: WMO
        Windows NT: WNT
        Windows Phone: WPH
        Windows RT: WRT
        Windows Server 2003: WS3
        Windows Vista: WVI
        Windows XP: WXP
        Xbox: XBX
        Xubuntu: XBT
        YunOs: YNS
        iOS: IOS
        palmOS: POS
        webOS: WOS