parameters:
    uap_mapping_browser:
        AB: 1
        AM: 2
        AN: 3
        AR: 4
        AV: 5
        AW: 6
        BB: 7
        BD: 8
        BE: 9
        BX: 10
        CA: 11
        CF: 12
        CH: 13
        CI: 14
        CK: 15
        CM: 16
        CO: 17
        CR: 18
        CS: 19
        DF: 20
        DI: 21
        EL: 22
        EP: 23
        FB: 24
        FD: 25
        FE: 26
        FF: 27
        FL: 28
        FN: 29
        GA: 30
        GE: 31
        HJ: 32
        IB: 33
        IC: 34
        IE: 35
        IM: 36
        IR: 37
        JS: 38
        KI: 39
        KM: 40
        KO: 41
        KP: 42
        KZ: 43
        LG: 44
        LI: 45
        LX: 46
        MB: 47
        MC: 48
        MF: 49
        MI: 50
        MS: 51
        MX: 52
        NB: 53
        NF: 54
        NL: 55
        NS: 56
        OB: 57
        OI: 58
        OM: 59
        OP: 60
        OV: 61
        OW: 62
        PL: 63
        PR: 64
        PX: 65
        RK: 66
        RM: 67
        SF: 68
        SM: 69
        SN: 70
        SX: 71
        TZ: 72
        UC: 73
        WO: 74
        YA: 75