parameters:
    uap_mapping_device_brand:
        # 0 is reserved for Null or Not Available
        # 1 is reserved for Unknown
        AI: 2
        AL: 3
        AO: 4
        AP: 5
        AU: 6
        AV: 7
        AX: 8
        BE: 9
        BI: 10
        BL: 11
        BQ: 12
        BS: 13
        CK: 14
        CL: 15
        CT: 16
        DB: 17
        DC: 18
        DI: 19
        DL: 20
        DP: 21
        EC: 22
        EI: 23
        ER: 24
        ET: 25
        EZ: 26
        FL: 27
        GI: 28
        GO: 29
        GR: 30
        GU: 31
        HA: 32
        HP: 33
        HT: 34
        HU: 35
        IK: 36
        IM: 37
        IN: 38
        IO: 39
        IQ: 40
        KA: 41
        KD: 42
        KN: 43
        KO: 44
        KY: 45
        LA: 46
        LC: 47
        LE: 48
        LG: 49
        LU: 50
        MI: 51
        MO: 52
        MR: 53
        MS: 54
        MT: 55
        MY: 56
        NE: 57
        NG: 58
        NI: 59
        NK: 60
        NW: 61
        NX: 62
        OD: 63
        OP: 64
        OR: 65
        OT: 66
        PA: 67
        PH: 68
        PM: 69
        PO: 70
        PT: 71
        QT: 72
        RM: 73
        RO: 74
        SA: 75
        SD: 76
        SE: 77
        SF: 78
        SG: 79
        SH: 80
        SI: 81
        SN: 82
        SO: 83
        SP: 84
        SY: 85
        TA: 86
        TC: 87
        TE: 88
        TH: 89
        TI: 90
        TM: 91
        TO: 92
        TS: 93
        UT: 94
        VD: 95
        VE: 96
        VI: 97
        VK: 98
        VO: 99
        WB: 100
        WE: 101
        WO: 102
        XX: 103
        ZO: 104
        ZT: 105
        AC: 106